### ISSUE TITLE
Query about automate the SSH access of steelconnect

### ISSUE THREAD

**Issue by Devraj004** [grelleum/SteelConnection#37]
Hi Sir,
I am trying to  automate the SSH access of steelconnect devices with the help of steelconnection and paramiko library.

I am able to start the tunnel of a node with Steelconnection  but then SSH access with Paramiko is getting failed.
Not sure if it is possible to get the SSH access with Paramiko.

Apologies for disturbing you. I tried a lot but no luck. 

Kind regards 
Devraj

**Comment by grelleum** [comment]
Hi Devraj,

There are a couple of requirements to do this.  

1. You need to have you ssh public key installed on the SCM.
2. You need to be on a Mac or Linux machine.  As far as I know, it will not work on Windows with Paramiko, at least not without creating a custom socket.  Additionally, it will be more difficult to run on CentOS 7 or 8 because they come with a different netcat (nc) client that uses different commands.

When you start a tunnel, you receive a command that allows you to ssh to the appliance - as long as you can run that command on the system where paramiko is installed you should be able to ssh to the appliance with paramiko.

```
import paramiko

# Insert appliance Serial number and realm below:
realm = "myrealm.riverbed.cc"
appliance = "XN0123456789ABCD"

# The f-string syntax assumes python 3.6 or higher.
hostname = f"{appliance}.{realm}"
proxy_command = f"nc -X connect -x {realm}:3903 {hostname} 22"

# Create a scoket for the proxied connection.
sock = paramiko.proxy.ProxyCommand(proxy_command)

# Create paramiko client.
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname=hostname, username="root", sock=sock)

# Execute the command "ip -4 a"
sdtin, stdout, stderr = client.exec_command("ip -4 a")
output = stdout.read().decode()
print(output)

# close the connection:
client.close()
```

**Comment by grelleum** [comment]
Hi Devraj,

I wanted to mention that I added a paramiko ssh script to the examples folder:
https://github.com/grelleum/SteelConnection/blob/develop/examples/ssh_to_appliance.py

Regards,
Greg
